# Site settings
title: Ahmed ElHassany
tag_text: Ahmed El-Hassany
description: I am a first year PhD student at ETH Zürich, advised by Laurent Vanbever. My research looks at how to make networks more programmable and how to verify correctness of programmable networks.


# Build settings
markdown: kramdown

exclude: ["README.md"]
